### ISSUE TITLE
Slopes not looping?

### ISSUE THREAD

**Issue by garethGeniusJones** [TomWhitwell/Workshop_Computer#10]
I can trigger slopes and get expected envelope shapes. Blip also works as expected (great little feature. Thanks). I cannot get slopes looping though. 😭

**Comment by TomWhitwell** [comment]
That strongly suggests you have a USB power supply that is sending 5Volts or 9Volts, but not 15 Volts 

Some power supplies - particularly batteries - are quite eccentric about this - they'll send 15V when one thing is connected, then drop down to 5V when something else is plugged in

**Comment by garethGeniusJones** [comment]
Looping mode now looping.  Thanks for your kind and speedy advice. I should just have used the power supply you told me to use!!
