### ISSUE TITLE
78 Talker Feedback

### ISSUE THREAD

**Issue by SentosRatos** [TomWhitwell/Workshop_Computer#5]
Hello, I've got an error -36 every time I want to put in the sd card !!!
Can you help me please?
In french : Le Finder ne peut pas terminer l’opération car certaines données de « 78_Talker.uf2 » ne peuvent pas être lues ou écrites.
(code d’erreur -36)
Thank you.

**Comment by chrisgjohnson** [comment]
Hmm - is this happening when you are trying to copy the uf2 onto your Computer? 

Does it only happen with the Talker, or with other cards too?

**Comment by chrisgjohnson** [comment]
Not certain, but https://www.ytyng.com/en/blog/raspberry-pi-pico-rp2040-mac-os-sonoma-copy-input-output-error/ looks potentially relevant

**Comment by TomWhitwell** [comment]
@SentosRatos Just to check - how are you connecting to the Workshop System - 
https://www.musicthing.co.uk/Computer_Program_Cards/#computer-faq
NB: You cannot read or write Program Cards in a normal SD Card reader - they're completely different connections and pins.
You can only write to the Program Card using the Workshop System itself, as described in that link: 

How do I write a blank program card?
- You will have downloaded a .uf2 file. This is the firmware.
- Pull off the main knob at the top of Computer (it’s stiff at first, gets easier quickly). Behind it you’ll see little button recessed into the panel.
- Put the card you want to write into the card slot. Check it’s the right one. Printed cards are not write protected, so you can write over a Reverb+ as easily as a Blank card.
- Connect a USB-C cable from the front panel USB port to your computer.
- Hold down the top button, then tap and release the bottom button next to the Program Card slot. If it doesn’t appear, turn the Workshop System off and on and try again.
- A folder called RPI-RP2 will appear on your desktop
- Drag the relevant .uf2 file onto the folder. The folder will disappear, and the firmware is updated.

**Comment by TomWhitwell** [comment]
Yes, let us know if you're on Sonoma

**Comment by SentosRatos** [comment]
Hello Tom,
Thank you for the fast answear.
The RP1-RP2 device is on my desktop but inside I can't find any .uf2, all
the small card are populated by locked INDEX.HTM and INFO_UF2.TXT .
When I try to copy a program downloaded, an error-36 appear.
I try on my wife's Mac computer, a more recent engine, and the same error
happened.
Could it be an building mistake ?
Thank a lot for your help,
it's very frustrating cause I adore the 2/3 of this system and I can't wait
to discover the brain of these wonderful muscles.

Le lun. 16 déc. 2024 à 09:46, Tom Whitwell ***@***.***> a
écrit :

**Comment by SentosRatos** [comment]
Yes, my computer with High Sierra doesn't permit to save .uf2 into the
card. it is an error code -36.
Finder cannot complete the operation because some data in
'euclidean_karplusstrong.uf2' cannot be read or written.
(error code -36)


Le lun. 16 déc. 2024 à 12:52, Tom Whitwell ***@***.***> a
écrit :

**Comment by TomWhitwell** [comment]
Have you tried the method described in the Sonoma article?

**Comment by SentosRatos** [comment]
Maybe not. Where could I find it please?

Le lun. 16 déc. 2024 à 13:50, Tom Whitwell ***@***.***> a
écrit :

**Comment by TomWhitwell** [comment]
And the Sonoma issue above does give error 36
https://www.ytyng.com/en/blog/raspberry-pi-pico-rp2040-mac-os-sonoma-copy-input-output-error/

**Comment by SentosRatos** [comment]
Wouaw it's more complex than I thought !! I am on High Sierra and I am really not familiar with console or terminal, but I'll give a try. Curious that I am the first to have this issue, don't you think?
Thank you very much for your support.

**Comment by SentosRatos** [comment]
Ok Thanks I'll give you some news. Have a good afternoon.
Best Regards.

**Comment by TomWhitwell** [comment]
Hi, as I asked earlier, have you tested the pre-programmed cards: (Reverb, Turing)?

They were written at Thonk (by me) before they were sent to you. 

If they don't work in the system - IE they do not work [as described here](https://www.musicthing.co.uk/Computer_Program_Cards/):  then it may be a hardware / soldering issue with your SD card holder. 

Tom

**Comment by SentosRatos** [comment]
Yes I've tested all the cards and they dont worked.
But when I see the RP1-RP2 on my computer, there is two folders but not the
.uf2, and it seem impossible to charge them.
Ok, I'am gonna try to resolder the sd container just to see.
Sorry for the time you spend to answer me.
Good evening.

Le mar. 17 déc. 2024, 16:54, Tom Whitwell ***@***.***> a
écrit :

**Comment by TomWhitwell** [comment]
OK definitely I think the problem is hardware in the module - the RP2040 chip cannot see the program cards. Check the soldering - send a clear photo of the back of the SD card holder pins

**Comment by SentosRatos** [comment]
Hi, I am so damned!!!! I tried to make new solders, they looks perfect and
when I plug the workshop on the computer,
my computer turn to black.
And now it doesn't want to work anymore, nothing to do.😱
Some current should burn my motherboard, via USB?!?
Horrible time for me sorry.
I send you some pics but my solders don't looks problematic.

Le mar. 17 déc. 2024, 18:23, Tom Whitwell ***@***.***> a
écrit :

**Comment by SentosRatos** [comment]
Hello Tom, 
I lost my 2 computer's USB ports and all my Workshop modular now. 
No sounds other than an horrible hiss came from it.
I would like to send the synth engine to your adress, if you don't mind.
Maybe this proto 1.0 have some issues?
I think it's better than photos, cause I really don't see any mistake on my soldering work.
Maybe we can find a commercial arrangement to buy you a new system, cause I can't stand this frustrating situation.
It's really not easy for me to spend all this money but I can't tolerate all these failures.
Let me know what you thinking please.
With all my respect,
Nicolas SENTENAC.

**Comment by TomWhitwell** [comment]
Hi Nicholas - I'm very sorry to hear that - we have over 200 workshop systems out in the world now and have never heard of any problems remotely like this so you have an extremely unusual situation. 
Before we arrange a return, please post high resolution photographs of
1. The back of all the PCBs so we can understand how they have been assembled
1. The component side of the PSU board so we can identify any damage caused 
1. Your power adaptor and cable that you used to power the workshop system - if possible, include a close up of any specifications on the power adaptor. This is the supply you used to power the system when it was connected to your MacBook. 
Either post those images here or email them to tom@musicthing.co.uk if that's easier for you 
Best wishes 
Tom

**Comment by SentosRatos** [comment]
Ok I'll made it tonight and send it to you after.

Le mer. 18 déc. 2024, 19:09, Tom Whitwell ***@***.***> a
écrit :
