### ISSUE TITLE
Extra unecessary build files included in repo

### ISSUE THREAD

**Issue by 4oo4** [TomWhitwell/Workshop_Computer#6]
It's probably worth adding `build/` to your `.gitignore` file, as currently it looks like there are lots of extra build output files included in the repo (example: https://github.com/TomWhitwell/Workshop_Computer/blob/main/Demonstrations%2BHelloWorlds/PicoSDK/Computer_HelloWorld/build/CMakeFiles/Computer_HelloWorld.dir/Computer_HelloWorld.c.obj.d).

Cheers

**Comment by TomWhitwell** [comment]
Thanks, added
