### ISSUE TITLE
08 Bytebeat Feedback

### ISSUE THREAD

**Issue by garethGeniusJones** [TomWhitwell/Workshop_Computer#7]
Here is some constructive and creative feedback

Cannot find the file to download. Link broken?

**Comment by chrisgjohnson** [comment]
Oh, link on https://www.musicthing.co.uk/Computer_Program_Cards/
is to the old repository - it should be to
[https://github.com/TomWhitwell/Workshop_Computer/raw/refs/heads/main/releases/08_bytebeat/uf2%20Installer/08_bytebeat.ino.uf2
](https://github.com/TomWhitwell/Workshop_Computer/raw/refs/heads/main/releases/08_bytebeat/uf2%20Installer/08_bytebeat.ino.uf2
)

**Comment by TomWhitwell** [comment]
Sorry Gareth, fixed now
