### ISSUE TITLE
Midi Card unexpected behaviour

### ISSUE THREAD

**Issue by garethGeniusJones** [TomWhitwell/Workshop_Computer#9]
I can calibrate theMidi Card it seems. But when I try to play Midi into the computer the first not sent changes the pitch as expected and sends a gate signal, and the left centre LED illumination the computer. Sending further midi notes has no effect on pitch and no gate signals are received.

Broken Midi Card?

**Comment by garethGeniusJones** [comment]
I re-installed the "Simple_Midi_0_5_0.ino.uf2" on the Midi Card. Same behaviour

**Comment by garethGeniusJones** [comment]
I installed "Simple_Midi_0_5_0.ino.uf2" on a fresh card. Same behaviour.

I must be missing something 🤔

**Comment by TomWhitwell** [comment]
Hi Gareth - sorry to hear that - what DAW are you using? 

Does the bottom LED flash on and off with the note on and off signals?

**Comment by TomWhitwell** [comment]
I wonder if this is to do with some midi hosts / DAWs sending Note On messages with zero velocity rather than note off messages. I can dig into it a bit more

**Comment by garethGeniusJones** [comment]
Tried Logic and Ableton. No LEDs flashing on Computer🌈 ☮️ 🙏🏽Garethhttps://linktr.ee/garethjonesnoisemakerOn 26 Dec 2024, at 22:55, Tom Whitwell ***@***.***> wrote:﻿
Hi Gareth - sorry to hear that - what DAW are you using?
Does the bottom LED flash on and off with the note on and off signals?

**Comment by TomWhitwell** [comment]
Assuming you see the Workshop System in the MIDI settings, and you're sending out on Channel 1 or 2 to that device: 
![image](https://github.com/user-attachments/assets/00fac85e-242e-4832-86eb-793c474f34cf)

**Comment by garethGeniusJones** [comment]
Yes I see the device “Workshop System MIDI” and I send on channel 1 or 2. As I mentioned the first MIDI message changes the pitch and sends a gate successfully. After that - no joy.

**Comment by garethGeniusJones** [comment]
I do not have the “Remote” checkbox ticked though. Just “Track”

**Comment by TomWhitwell** [comment]
OK that shouldn't make a difference - I'll ask the wider community if anyone else is seeing anything similar, see if we can get to the bottom of it. Also tagging @Thonk-Devan who is looking at MIDI implementation right now to see if she can spot anything weird in my cranky code

**Comment by garethGeniusJones** [comment]
This works fine with my iPad! Using midiSequencer. Will research with the laptop more later. And report back. I wonder how cc42 is mapped to voltage? It’s working but I’m struggling a little with the resolution.

**Comment by TomWhitwell** [comment]
Ah that's good news. Yes, the CC voltage will be quite crude - -6 to +6, with 64 approximately 0v (from memory)

**Comment by garethGeniusJones** [comment]
My problem seems to be that the computer is streaming a bunch of MIDI back to the DAW. If I turn off the INPUT “workshop system Midi” then midi notes from my DAW play as expected.  Tested now with Logic

**Comment by garethGeniusJones** [comment]
The midi computer is sending the midi notes from the DAW back to the DAW. Leading to weird Midi feedback unless I am careful. Unexpected behaviour.
